static pointer CLO5476();
static pointer FLET5507();
static pointer UWP5533();
static pointer CLO5538();
static pointer CLO5542();
static pointer CLO5559();
static pointer CLO5563();
static pointer CLO5564();
static pointer CLO5566();
static pointer CLO5569();
static pointer CLO5571();
static pointer CLO5572();
static pointer CLO5576();
static pointer CLO5578();
static pointer CLO5579();
static pointer CLO5591();
static pointer CLO5595();
static pointer CLO5598();
static pointer CLO5600();
static pointer CLO5601();
static pointer CLO5602();
static pointer CLO5603();
static pointer CLO5606();
static pointer CLO5607();
static pointer CLO5608();
static pointer CLO5609();
static pointer CLO5610();
static pointer CLO5611();
static pointer CLO5612();
static pointer CLO5615();
static pointer CLO5629();
static pointer CLO5636();
static pointer (*ftab[44])();

#define QUOTE_STRINGS_SIZE 604
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "collada::*collada-print-customize-symbols*",
    "find",
    "string",
    "string-downcase",
    "\"~s\"",
    "concatenate",
    "\" \"",
    "\"=\\\"\"",
    "cadar",
    "\"\\\"\"",
    "caadr",
    "collada::@",
    "collada::bo",
    "cdadr",
    "\"\"",
    "collada::bc",
    "collada::eo",
    "collada::ec",
    "\"<\"",
    "\"</\"",
    "(collada::bc collada::ec)",
    "\">~%\"",
    "\"<\"",
    "\"</\"",
    "(collada::bc collada::ec)",
    "\">~%\"",
    "\"<\"",
    "\"</\"",
    "(collada::bc collada::ec)",
    "\"~%\"",
    "make-string",
    "\">\"",
    ":links",
    ":joint-list",
    ":name",
    "send-all",
    ":jointid",
    ":test",
    "string=",
    "remove-duplicates",
    "\"NOT UNIQUE NAMES ~A\"",
    "collada::eusmodel-link-spec",
    "collada::eusmodel-joint-spec",
    "user::acentroid",
    ":inertia-tensor",
    ":parent",
    ":worldcoords",
    ":copy-worldcoords",
    ":translate",
    ":transformation",
    "user::sv-decompose",
    ":rotate",
    ":origin",
    ":mesh",
    ":mass_frame",
    ":mass",
    ":weight",
    ":inertia",
    ":bodies",
    "faceset",
    ":init",
    ":faces",
    "body-to-triangles",
    ":set-color",
    ":face-color",
    ":move-to",
    ":inverse-transformation",
    ":type",
    "user::rotational-joint",
    ":rotational-joint",
    "user::linear-joint",
    ":linear-joint",
    ":id",
    ":limit",
    ":axis",
    "user::axis",
    ":x",
    "#f(1.0 0.0 0.0)",
    ":y",
    "#f(0.0 1.0 0.0)",
    ":z",
    "#f(0.0 0.0 1.0)",
    ":xx",
    "#f(1.0 0.0 0.0)",
    ":yy",
    "#f(0.0 1.0 0.0)",
    ":zz",
    "#f(0.0 0.0 1.0)",
    ":-x",
    "#f(-1.0 0.0 0.0)",
    ":-y",
    "#f(0.0 -1.0 0.0)",
    ":-z",
    "#f(0.0 0.0 -1.0)",
    "#f(0.0 0.0 0.0)",
    ":parent-link",
    ":child",
    ":child-link",
    ":upper",
    ":max-angle",
    "deg2rad",
    ":lower",
    ":min-angle",
    ":head",
    ":larm",
    ":rarm",
    ":lleg",
    ":rleg",
    "\"head\"",
    "\"larm\"",
    "\"rarm\"",
    "\"lleg\"",
    "\"rleg\"",
    "find-method",
    ":end-coords",
    ":link-list",
    "#(:scale)",
    "\"start converting to collada sxml~%\"",
    "warn",
    "collada::collada",
    "collada::version",
    "\"1.5.0\"",
    "collada::xmlns",
    "\"http://www.collada.org/2008/03/COLLADASchema\"",
    "collada::asset",
    "collada::contributor",
    "collada::authoring_tool",
    "\"Eus2Collada\"",
    "collada::unit",
    "collada::meter",
    "name",
    "\"millimeter\"",
    "collada::up_axis",
    "\"Z_UP\"",
    "probe-file",
    ":directory",
    "\"~A must be a directory\"",
    "(0)",
    "#(:scale :file-suffix)",
    "\".dae\"",
    "\"You need to specify name\"",
    "body",
    "bodyset",
    "user::cascaded-link",
    "user::bodyset-link",
    "make-cascoords",
    "user::links",
    ":assoc",
    ":init-ending",
    ":scale",
    "\"~A/~A.dae\"",
    ":direction",
    ":output",
    "open",
    "\"<?xml version=\\\"1.0\\\"?>~%\"",
    "\"~A.node\"",
    "assoc",
    "\"~A_node\"",
    "collada::library_materials",
    "id",
    "\"libmat\"",
    "collada::link-description->collada-materials",
    "\"~A.geometry\"",
    "\"~A.effect\"",
    "\"~A.~A.material\"",
    "\"~A.~A\"",
    "collada::material",
    "collada::instance_effect",
    "collada::url",
    "\"#~A\"",
    "collada::library_effects",
    "\"libeffect\"",
    "collada::link-description->collada-effects",
    "\"~A.effect\"",
    "\"~A.~A\"",
    "\";; please set face-color for meshes ~A~%\"",
    "collada::effect",
    "collada::|profile_COMMON|",
    "collada::technique",
    "collada::sid",
    "\"common\"",
    "collada::phong",
    "collada::ambient",
    "collada::color",
    "\"~A ~A ~A 1.0\"",
    "collada::diffuse",
    "\"~A ~A ~A 1.0\"",
    "array-dimensions",
    "make-string-output-stream",
    "\"~A \"",
    "\"~%\"",
    "get-output-stream-string",
    "null",
    "remove-if",
    "collada::rotate",
    "\"~A_axis0\"",
    "\"1 0 0 0\"",
    "position-if",
    "collada::node",
    "\"node~D\"",
    "collada::instance_geometry",
    "\"#~A.~A\"",
    "collada::bind_material",
    "collada::technique_common",
    "collada::instance_material",
    "symbol",
    "\"~A.~A.material\"",
    "collada::target",
    "\"#~A.~A.material\"",
    "collada::library_visual_scenes",
    "\"vscenes\"",
    "collada::visual_scene",
    "\"vscene\"",
    "\"Eus2Collada Visual Scene\"",
    "\"visual1\"",
    "\"visual1\"",
    "\"#~A\"",
    "\"~A.geometry.~A.material\"",
    "collada::library_kinematics_scenes",
    "\"kscenes\"",
    "collada::kinematics_scene",
    "\"kscene\"",
    "\"Eus2Collada Kinematics Scene\"",
    "collada::instance_articulated_system",
    "\"robot1_motion_inst\"",
    "\"#robot1_motion\"",
    "collada::newparam",
    "\"kscene_kmodel1_inst\"",
    "\"<SIDREF>robot1_motion/robot1_motion.kmodel1_inst</SIDREF>\"",
    "\"kscene_kmodel1_inst.~A_axis0\"",
    "\"<SIDREF>robot1_motion/robot1_motion.kmodel1_inst.inst_~A_axis0</SIDREF>\"",
    "\"kscene_kmodel1_inst.~A.value\"",
    "\"<SIDREF>robot1_motion/robot1_motion.kmodel1_inst.inst_~A_value</SIDREF>\"",
    "collada::library_kinematics_models",
    "\"kmodels\"",
    "collada::kinematics_model",
    "\"kmodel1\"",
    "collada::library_physics_scenes",
    "\"pscenes\"",
    "collada::physics_scene",
    "\"pscene\"",
    "\"Eus2Collada Physics Scene\"",
    "collada::instance_physics_model",
    "\"#pmodel1\"",
    "\"pmodel1\"",
    "collada::parent",
    "\"#visual1\"",
    "collada::instance_rigid_body",
    "collada::body",
    "\"rigid~a\"",
    "\"#~a\"",
    "collada::library_physics_models",
    "\"pmodels\"",
    "collada::physics_model",
    "\"pmodel1\"",
    "\"rigid~a\"",
    "\"rigid~a\"",
    "collada::rigid_body",
    "\"~a\"",
    "\"~a\"",
    "\"~a_link\"",
    "collada::mass",
    "\"~A\"",
    "collada::mass_frame",
    "collada::translate",
    ":worldpos",
    ":worldrot",
    "collada::inertia",
    "collada::shape",
    "\"#~a.geometry.~a\"",
    "\"0 0 0\"",
    "\"0 0 1 0\"",
    ":key",
    "remove-if-not",
    "user::matrix2quaternion",
    "normalize-vector",
    "expt",
    "rad2deg",
    "collada::library_articulated_systems",
    "\"asystems\"",
    "collada::articulated_system",
    "\"robot1_motion\"",
    "collada::motion",
    "\"#robot1_kinematics\"",
    "\"robot1_motion.kmodel1_inst\"",
    "\"<SIDREF>robot1_kinematics/robot1_motion_kmodel1_inst</SIDREF>\"",
    "\"robot1_kinematics\"",
    "collada::kinematics",
    "collada::instance_kinematics_model",
    "\"#kmodel1\"",
    "\"kmodel1_inst\"",
    "\"robot1_motion_kmodel1_inst\"",
    "\"<SIDREF>robot1_kinematics/kmodel1_inst</SIDREF>\"",
    "\"robot1_motion.kmodel1_inst.inst_~A_axis0\"",
    "\"<SIDREF>robot1_kinematics/robot1_motion_kmodel1_inst.~A_axis0</SIDREF>\"",
    "\"robot1_motion.kmodel1_inst.inst_~A_value\"",
    "\"<SIDREF>robot1_motion_kmodel1_inst.~A.value</SIDREF>\"",
    "collada::axis_info",
    "collada::axis",
    "\"robot1_kinematics/~A_info\"",
    "\"robot1_motion_kmodel1_inst.~A_axis0\"",
    "\"<SIDREF>robot1_kinematics/kmodel1_inst/~A/axis0</SIDREF>~%\"",
    "\"robot1_motion_kmodel1_inst.~A.value\"",
    "float",
    "\"0\"",
    "\"kmodel1/~A/axis0\"",
    "\"~A_info\"",
    "last",
    "collada::extra",
    "type",
    "\"manipulator\"",
    "collada::profile",
    "\"OpenRAVE\"",
    "collada::frame_origin",
    "collada::link",
    "\"kmodel1/~A_link\"",
    "collada::frame_tip",
    "\"kmodel1/~A_link\"",
    "\"~A_link\"",
    "\"~A_link\"",
    "collada::attachment_full",
    "collada::joint",
    "\"kmodel1/~A\"",
    "collada::joint-description->collada-instance-joint",
    "collada::instance_joint",
    "\"#~A\"",
    "collada::library_joints",
    "\"libjoints\"",
    "collada::joint-description->collada-joint",
    "\"~A\"",
    "\"~A\"",
    "\"jointsid~A\"",
    "\"~A is not supported for collada converter\"",
    "collada::prismatic",
    "\"axis0\"",
    "collada::limits",
    "min",
    "\"~A\"",
    "max",
    "\"~A\"",
    "collada::revolute",
    "\"axis0\"",
    "\"~A\"",
    "\"~A\"",
    "collada::scene",
    "collada::instance_physics_scene",
    "\"#pscene\"",
    "collada::instance_visual_scene",
    "\"#vscene\"",
    "collada::instance_kinematics_scene",
    "\"#kscene\"",
    "collada::bind_kinematics_model",
    "\"visual1/node0\"",
    "collada::param",
    "\"kscene_kmodel1_inst\"",
    "collada::bind_joint_axis",
    "\"~A.node/~A_axis0\"",
    "\"kscene_kmodel1_inst.~A_axis0\"",
    "value",
    "\"kscene_kmodel1_inst.~A.value\"",
    "collada::library_geometries",
    "\"libgeom\"",
    "\"~A.geometry\"",
    "\"~A_geometry\"",
    "collada::link-description->collada-geometry",
    "collada::mesh",
    "collada::source",
    "\"~A.positions\"",
    "collada::float_array",
    "\"~A.positions.float-array\"",
    "count",
    "collada::accessor",
    "\"#~A.positions.float-array\"",
    "collada::stride",
    "\"3\"",
    "\"X\"",
    "\"float\"",
    "\"Y\"",
    "\"float\"",
    "\"Z\"",
    "\"float\"",
    "\"~A.normals\"",
    "\"~A.normals.float-array\"",
    "\"#~A.normals.float-array\"",
    "\"3\"",
    "\"X\"",
    "\"float\"",
    "\"Y\"",
    "\"float\"",
    "\"Z\"",
    "\"float\"",
    "collada::vertices",
    "\"~A.vertices\"",
    "collada::input",
    "collada::semantic",
    "\"POSITION\"",
    "\"#~A.positions\"",
    "collada::triangles",
    "\"~A.material\"",
    "collada::offset",
    "\"0\"",
    "\"VERTEX\"",
    "\"~A.vertices\"",
    "\"1\"",
    "\"NORMAL\"",
    "\"~A.normal\"",
    "\"~A.~A\"",
    "\"~A.~A\"",
    "collada::geometry",
    "\"<p>\"",
    ":vertices",
    "\"~A \"",
    "\"~A \"",
    "\"~%\"",
    "\"</p>~%\"",
    "\"~A \"",
    "\"~%\"",
    ":normal",
    "\"~A \"",
    "\"~%\"",
    "\"~A \"",
    "\"~%\"",
    "matrix-column",
    "matrix",
    "remove",
    "user::matrix-determinant",
    "pathname",
    "pathname-name",
    "string-upcase",
    "\"~A.~A\"",
    "pathname-type",
    "\"./\"",
    "truename",
    ":namestring",
    "\"convert ~A and output to ~A~%\"",
    "\"loading ~A~%\"",
    "load",
    "exit",
    ":irtmodel",
    "require",
    "\"COLLADA\"",
    "\"COLLADA\"",
    "make-package",
    "\"COLLADA\"",
    "\"COLLADA\"",
    "*package*",
    "\"no such package\"",
    ":vtype",
    ":global",
    "(collada::collada collada::|profile_COMMON|)",
    "collada::symbol->string",
    "\"(sym)\"",
    "collada::->string",
    "\"(val)\"",
    "collada::string-append",
    "\"(&rest args)\"",
    "collada::make-attr",
    "\"(l ac)\"",
    "collada::make-xml",
    "\"(x bef aft)\"",
    "collada::sxml->xml",
    "\"(sxml)\"",
    "collada::xml-output-to-string-stream",
    "\"(ss l)\"",
    "collada::cat-normal",
    "\"(l s)\"",
    "collada::cat-clark",
    "\"(l s i)\"",
    "collada::eusmodel-description",
    "\"convert a `model' to eusmodel-description\"",
    "collada::verificate-unique-strings",
    "\"(names)\"",
    "collada::eusmodel-link-specs",
    "\"convert `links' to <link-specs>\"",
    "collada::eusmodel-joint-specs",
    "\"convert `joints' to <joint-specs>\"",
    "\"(link)\"",
    "collada::eusmodel-mesh-spec",
    "\"(link)\"",
    "\"(_joint)\"",
    "collada::eusmodel-limit-spec",
    "\"(_joint)\"",
    "collada::eusmodel-endcoords-specs",
    "\"(model)\"",
    "collada::eusmodel-link-description",
    "\"(description)\"",
    "collada::eusmodel-joint-description",
    "\"(description)\"",
    "collada::eusmodel-endcoords-description",
    "\"(description)\"",
    "collada::eusmodel-description->collada",
    "\"convert eusmodel-descrption to collada sxml\"",
    "collada::setup-collada-filesystem",
    "\"(obj-name base-dir)\"",
    "collada::range2",
    "\"(n)\"",
    "collada::eus2collada",
    "\"(obj full-root-dir &key (scale 0.001) (file-suffix \\\".dae\\\"))\"",
    "collada::collada-node-id",
    "\"(link-descrption)\"",
    "collada::collada-node-name",
    "\"(link-descrption)\"",
    "collada::links-description->collada-library-materials",
    "\"(links-desc)\"",
    "\"(link-desc)\"",
    "collada::mesh-description->collada-material",
    "\"(mat effect)\"",
    "collada::links-description->collada-library-effects",
    "\"(links-desc)\"",
    "\"(link-desc)\"",
    "collada::mesh-description->collada-effect",
    "\"(mesh id)\"",
    "collada::matrix->collada-string",
    "\"(mat)\"",
    "collada::find-parent-liks-from-link-description",
    "\"(target-link desc)\"",
    "collada::eusmodel-description->collada-node-transformations",
    "\"(target-link desc)\"",
    "collada::eusmodel-description->collada-node",
    "\"(target-link desc)\"",
    "collada::eusmodel-description->collada-library-visual-scenes",
    "\"(name desc)\"",
    "collada::mesh-description->instance-material",
    "\"(s)\"",
    "collada::link-description->collada-bind-material",
    "\"(link)\"",
    "collada::eusmodel-description->collada-library-kinematics-scenes",
    "\"(name desc)\"",
    "collada::eusmodel-description->collada-library-kinematics-models",
    "\"(name desc)\"",
    "collada::eusmodel-description->collada-kinematics-model",
    "\"(name desc)\"",
    "collada::eusmodel-description->collada-library-physics-scenes",
    "\"(name desc)\"",
    "collada::eusmodel-description->collada-library-physics-models",
    "\"(name desc)\"",
    "collada::find-root-link-from-joints-description",
    "\"(joints-description)\"",
    "collada::find-link-from-links-description",
    "\"(name links-description)\"",
    "collada::eusmodel-description->collada-links",
    "\"(description)\"",
    "collada::find-joint-from-link-description",
    "\"(target joints)\"",
    "collada::find-child-link-descriptions",
    "\"(parent links joints)\"",
    "collada::matrix->collada-rotate-vector",
    "\"convert a rotation matrix to axis-angle.\"",
    "collada::eusmodel-description->collada-library-articulated-systems",
    "\"(desc name)\"",
    "collada::eusmodel-endcoords-description->openrave-manipulator",
    "\"(end-coords description)\"",
    "collada::eusmodel-description->collada-links-tree",
    "\"(target links joints)\"",
    "collada::joints-description->collada-instance-joints",
    "\"(joints-desc)\"",
    "\"(joint-desc)\"",
    "collada::eusmodel-description->collada-library-joints",
    "\"(description)\"",
    "collada::joints-description->collada-joints",
    "\"(joints-description)\"",
    "collada::collada-joint-id",
    "\"(joint-description)\"",
    "\"(joint-description)\"",
    "collada::linear-joint-description->collada-joint",
    "\"(joint-description)\"",
    "collada::rotational-joint-description->collada-joint",
    "\"(joint-description)\"",
    "collada::eusmodel-description->collada-scene",
    "\"(description)\"",
    "collada::eusmodel-description->collada-library-geometries",
    "\"(description)\"",
    "collada::collada-geometry-id-base",
    "\"(link-descrption)\"",
    "collada::collada-geometry-name-base",
    "\"(link-descrption)\"",
    "collada::links-description->collada-geometries",
    "\"(links-description)\"",
    "collada::mesh-object->collada-mesh",
    "\"(mesh id)\"",
    "\"(link-description)\"",
    "collada::mesh->collada-indices",
    "\"(mesh)\"",
    "collada::mesh-vertices->collada-string",
    "\"(mesh)\"",
    "collada::mesh-normals->collada-string",
    "\"(mesh)\"",
    "collada::float-vector->collada-string",
    "\"(v)\"",
    "collada::enum-integer-list",
    "\"(n)\"",
    "collada::search-minimum-rotation-matrix",
    "\"(mat)\"",
    "collada::estimate-class-name",
    "\"(model-file)\"",
    "collada::remove-directory-name",
    "\"(fname)\"",
    "collada::convert-irtmodel-to-collada",
    "\"convert irtmodel to collada model. (convert-irtmodel-to-collada irtmodel-file-path &optional (output-full-dir (send (truename \\\"./\\\") :namestring)) (model-name))\"",
    "\"GEOMETRY\"",
    "\"GEOMETRY\"",
    "\"no such package\"",
    ":irtcollada",
    "provide",
  };
