static pointer (*ftab[12])();

#define QUOTE_STRINGS_SIZE 35
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "probe-file",
    "pathname-type",
    "\"jpg\"",
    "string=",
    "\"jpeg\"",
    "read-jpeg-file",
    "\"png\"",
    "read-png-file",
    "\"pbm\"",
    "\"pgm\"",
    "\"ppm\"",
    ":test",
    "member",
    "read-pnm-file",
    "\";; Unknown file format ~A~%\"",
    "warn",
    "\";; Could not find file ~A~%\"",
    "\"jpg\"",
    "\"jpeg\"",
    "write-jpeg-file",
    "\"png\"",
    "write-png-file",
    "write-pnm-file",
    "\"IMAGE\"",
    "\"IMAGE\"",
    "*package*",
    "\"no such package\"",
    "(read-image-file write-image-file)",
    "read-image-file",
    "\"read image of given fname. It returns instance of {\\\\bf grayscale-image} or {\\\\bf color-image24}.\"",
    "write-image-file",
    "\"write img to given fname\"",
    ":irtimage",
    "\"@(#)$Id$\"",
    "provide",
  };
