static pointer CLO144();
static pointer CLO150();
static pointer (*ftab[28])();

#define QUOTE_STRINGS_SIZE 144
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    "*display*",
    "\";; (window-main-one ~A) was called, but no display is found.~%\"",
    "warning-message",
    ":window-main-loop",
    "eventsqueued",
    "event",
    "nextevent",
    "*xevent-debug*",
    "print-event",
    "*skip-motion-event*",
    "event-type",
    "pending",
    "event2",
    "peekevent",
    "xevent-type",
    "xevent-window",
    "*skipped-event-count*",
    "process-event",
    "xflush",
    "xevent-state",
    "send",
    ":create-org",
    "\"WM_DELETE_WINDOW\"",
    "internatom",
    "setwmprotocols",
    "(:clientmessage)",
    "member",
    ":event-notify-dispatch",
    ":event-notify-org",
    ":destroy",
    "sync",
    ":destroyed",
    ":quit",
    ":event-procs",
    "event-left",
    ":buttonrelease-left",
    "assoc",
    "event-right",
    ":buttonrelease-right",
    "event-middle",
    ":buttonrelease-middle",
    ":buttonrelease-far",
    ":buttonrelease-near",
    ":motionnotify-left",
    ":motionnotify-right",
    ":motionnotify-middle",
    ":buttonpress",
    "send-message",
    "super",
    ":draw-pattern",
    ":create",
    "panel-tab-button-item",
    ":change-tabbed-panel",
    ":map",
    ":parent",
    ":locate-item",
    ":state",
    ":up",
    ":down",
    "send-all",
    "panel",
    ":x",
    ":y",
    ":width",
    ":height",
    ":name",
    ":tabbed-panel",
    ":unmap",
    ":draw-label",
    ":tabbed-button",
    ":key",
    ":test",
    "equal",
    ":resize",
    ":expose",
    ":foreground",
    "*fg-pixel*",
    ":draw-polygon",
    ":string",
    ":flush",
    "\"X\"",
    "\"X\"",
    "*package*",
    "\"no such package\"",
    ":motionnotify",
    ":configurenotify",
    "window-main-one",
    "\"(&optional fd)\"",
    "lisp::*use-top-selector*",
    "*top-selector*",
    ":remove-port",
    "display-fd",
    ":add-port",
    "probe-file",
    "load-foreign",
    "system::sysmod",
    "\"XSetWMProtocols\"",
    "nil",
    ":integer",
    "make-foreign-code",
    "xwindow",
    ":methods",
    ":event-notify",
    "event-far",
    "\"(e)\"",
    "event-near",
    "\"(e)\"",
    "\"(self class &rest args)\"",
    "\"(self class type event)\"",
    "\"(self class &rest a)\"",
    ":clientmessage",
    "\"(self class event)\"",
    ":set-event-proc",
    "\"(self class type method receiver)\"",
    ":buttonrelease",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class event)\"",
    "\"(self class &rest args)\"",
    ":redraw",
    "xscroll-bar",
    "\"(self class)\"",
    "tabbed-panel",
    ":global",
    ":super",
    ":slots",
    "(tabbed-buttons tabbed-panels selected-tabbed-panel)",
    ":metaclass",
    ":element-type",
    ":size",
    ":documentation",
    "make-class",
    "\"(self class &rest args)\"",
    ":add-tabbed-panel",
    "\"(self class name)\"",
    "\"(self class obj)\"",
    "\"(self class name &rest args)\"",
    "\"(self class name &rest args)\"",
    "\"(self class w h)\"",
    "button-item",
    "\"(self class &optional (state :up) (offset 0))\"",
    ":irtx",
    "\"$Id$\"",
    "provide",
  };
